-- HiveMind topology discovery
--
-- Writes lib/config.lua for you instead of making you count block faces.
--
-- Every transposer is asked what sits on each of its six sides through
-- getInventoryName(), which returns the inventory's registry name. That is
-- enough to tell a Genetic Sampler from a Replicator from the ME Interface, so
-- the machine links can be generated rather than hand-written. The same trick
-- finds the template chest.
--
-- READ ONLY: it looks, it prints, it writes one configuration file. Nothing in
-- the world is moved.
--
-- Usage:
--   discover              show what was found
--   discover --write      also write lib/config_topology.lua

local component = require("component")
local sides = require("sides")

local SIDE_NAMES = {
    [0] = "bottom/down", [1] = "top/up", [2] = "north/back",
    [3] = "south/front", [4] = "west/right", [5] = "east/left",
}

-- Registry name fragments -> the machine key used in lib/config.lua.
-- Ordered from most specific to least: "industrial_apiary" must be tested
-- before "apiary", and the Gendustry "transposer" before anything generic.
local SIGNATURES = {
    {pattern = "advanced_mutatron",   machine = "mutatron"},
    {pattern = "mutatron",            machine = "mutatron"},
    {pattern = "industrial_apiary",   machine = "breeding_apiary"},
    {pattern = "apiary",              machine = "breeding_apiary"},
    {pattern = "genetic_sampler",     machine = "sampler"},
    {pattern = "sampler",             machine = "sampler"},
    {pattern = "genetic_transposer",  machine = "genetic_transposer"},
    {pattern = "transposer",          machine = "genetic_transposer"},
    {pattern = "genetic_imprinter",   machine = "imprinter"},
    {pattern = "imprinter",           machine = "imprinter"},
    {pattern = "genetic_replicator",  machine = "replicator"},
    {pattern = "replicator",          machine = "replicator"},
    {pattern = "dna_extractor",       machine = "dna_extractor"},
    {pattern = "extractor",           machine = "dna_extractor"},
    {pattern = "protein",             machine = "protein_liquifier"},
    {pattern = "liquifier",           machine = "protein_liquifier"},
    {pattern = "mutagen",             machine = "mutagen_producer"},
    {pattern = "interface",           machine = "_me_interface"},
    {pattern = "chest",               machine = "_chest"},
}

local report = {}

local function say(text)
    text = text or ""
    table.insert(report, text)
    print(text)
end

--- Call a component method defensively
--- Component methods are callable tables, not functions, so only nil is ruled
--- out here and the call itself decides.
local function call(proxy, method, ...)
    if not proxy then return nil end

    local target = proxy[method]
    if target == nil then return nil end

    local ok, result = pcall(target, ...)
    if not ok then return nil end

    return result
end

--- Guess which machine an inventory name refers to
--- @param name string Registry or display name
--- @return string|nil machine
local function identify(name)
    if type(name) ~= "string" or name == "" then return nil end

    local lowered = name:lower()
    for _, signature in ipairs(SIGNATURES) do
        if lowered:find(signature.pattern, 1, true) then
            return signature.machine
        end
    end

    return nil
end

--- Every transposer on the network, in a stable order
--- @return table[] transposers {proxy, address}
local function findTransposers()
    local found = {}

    for address, kind in component.list("transposer") do
        table.insert(found, {address = address, proxy = component.proxy(address)})
    end

    table.sort(found, function(a, b) return a.address < b.address end)
    return found
end

--- Probe the six sides of one transposer
--- @param transposer table
--- @return table[] neighbours {side, name, size, machine}
local function probe(transposer)
    local neighbours = {}

    for side = 0, 5 do
        local name = call(transposer.proxy, "getInventoryName", side)
        local size = call(transposer.proxy, "getInventorySize", side)

        if name or size then
            table.insert(neighbours, {
                side = side,
                name = name or "?",
                size = tonumber(size) or 0,
                machine = identify(name),
            })
        end
    end

    return neighbours
end

--- Render the discovered topology as a Lua configuration fragment
--- @param discovered table
--- @return string source
local function renderConfig(discovered)
    local lines = {
        "-- HiveMind topology, generated by tools/discover.lua",
        "-- Regenerate after moving a machine; do not hand-edit both.",
        "",
        "local sides = require(\"sides\")",
        "",
        "return {",
        "    transposers = {",
    }

    for _, entry in ipairs(discovered.transposers) do
        table.insert(lines, string.format("        %q,", entry.address))
    end

    table.insert(lines, "    },")
    table.insert(lines, "")
    table.insert(lines, "    machines = {")

    local names = {}
    for name in pairs(discovered.machines) do table.insert(names, name) end
    table.sort(names)

    for _, name in ipairs(names) do
        local link = discovered.machines[name]
        table.insert(lines, string.format(
            "        %s = {transposer = %d, machine = %d, source = %s},  -- %s",
            name, link.transposer, link.machine,
            link.source and tostring(link.source) or "nil",
            link.inventory or "?"))
    end

    table.insert(lines, "    },")

    if discovered.templateChest then
        table.insert(lines, "")
        table.insert(lines, string.format(
            "    template_chest = {transposer = %d, side = %d, slots = %d},",
            discovered.templateChest.transposer,
            discovered.templateChest.side,
            discovered.templateChest.size))
    end

    table.insert(lines, "}")

    return table.concat(lines, "\n") .. "\n"
end

local function main(args)
    local write = false
    for _, arg in ipairs(args) do
        if arg == "--write" then write = true end
    end

    say("=========================================")
    say("  HiveMind - decouverte de la topologie")
    say("=========================================")
    say("")

    local transposers = findTransposers()

    if #transposers == 0 then
        say("Aucun transposer trouve.")
        say("")
        say("Le Transposer est la seule piece capable de deplacer des items.")
        say("Pose-en un contre chaque machine a alimenter, et relie-le au reseau")
        say("(le contact direct avec un autre bloc OpenComputers suffit).")
        return
    end

    say(#transposers .. " transposer(s) sur le reseau.")

    local discovered = {transposers = {}, machines = {}, templateChest = nil}
    local unknown = {}

    for index, transposer in ipairs(transposers) do
        table.insert(discovered.transposers, {address = transposer.address})

        say("")
        say("-- transposer " .. index .. " (" .. transposer.address:sub(1, 8) .. ") --")

        local neighbours = probe(transposer)

        if #neighbours == 0 then
            say("  aucun inventaire adjacent")
        end

        -- The ME Interface is the source side for every machine on this
        -- transposer: it is where items come from.
        local interfaceSide = nil
        for _, neighbour in ipairs(neighbours) do
            if neighbour.machine == "_me_interface" then
                interfaceSide = neighbour.side
            end
        end

        for _, neighbour in ipairs(neighbours) do
            local label = SIDE_NAMES[neighbour.side] or tostring(neighbour.side)
            local verdict

            if neighbour.machine == "_me_interface" then
                verdict = "ME Interface (source)"
            elseif neighbour.machine == "_chest" then
                verdict = "coffre"
                if not discovered.templateChest then
                    discovered.templateChest = {
                        transposer = index, side = neighbour.side, size = neighbour.size,
                    }
                    verdict = "coffre -> propose comme coffre a templates"
                end
            elseif neighbour.machine then
                verdict = neighbour.machine
                discovered.machines[neighbour.machine] = {
                    transposer = index,
                    machine = neighbour.side,
                    source = interfaceSide,
                    inventory = neighbour.name,
                }
            else
                verdict = "NON RECONNU"
                table.insert(unknown, neighbour.name)
            end

            say(string.format("  %-14s %-38s %s", label, neighbour.name, verdict))
        end

        if not interfaceSide then
            say("  ATTENTION: aucune ME Interface vue depuis ce transposer.")
            say("  Les machines qu'il dessert n'auront pas de source d'items.")
        end
    end

    say("")
    say("=== RESUME ===")

    local recognized = 0
    for _ in pairs(discovered.machines) do recognized = recognized + 1 end
    say(recognized .. " machine(s) reconnue(s).")

    local expected = {
        "mutatron", "breeding_apiary", "sampler", "genetic_transposer",
        "imprinter", "replicator", "dna_extractor", "protein_liquifier",
        "mutagen_producer",
    }

    local missing = {}
    for _, name in ipairs(expected) do
        if not discovered.machines[name] then table.insert(missing, name) end
    end

    if #missing > 0 then
        say("Pas encore vues : " .. table.concat(missing, ", "))
    end

    if #unknown > 0 then
        say("")
        say("Inventaires non reconnus (dis-les moi, j'ajouterai leur signature) :")
        for _, name in ipairs(unknown) do say("  " .. name) end
    end

    if not discovered.templateChest then
        say("")
        say("Aucun coffre vu: il en faut un, dedie aux templates.")
    end

    local source = renderConfig(discovered)

    say("")
    say("=== CONFIGURATION GENEREE ===")
    say(source)

    if write then
        local file, err = io.open("/home/hivemind_topology.lua", "w")
        if file then
            file:write(source)
            file:close()
            say("Ecrite dans /home/hivemind_topology.lua")
        else
            say("Ecriture impossible: " .. tostring(err))
        end
    else
        say("(relance avec --write pour l'ecrire dans un fichier)")
    end

    local out = io.open("/home/hivemind-topology.txt", "w")
    if out then
        out:write(table.concat(report, "\n") .. "\n")
        out:close()
        print("")
        print("Rapport complet : /home/hivemind-topology.txt")
    end
end

main({...})
